version: '3.8'

services:
  cassandra-node1:
    image: cassandra:4.1
    container_name: cassandra-node1
    networks:
      cass-net:
        aliases:
          - cassandra-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=meu_cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node1
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    volumes:
      - cassandra-data1:/var/lib/cassandra
    ports:
      - "9042:9042"       # cqlsh
      - "7199:7199"       # JMX (nodetool)
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra-node2:
    image: cassandra:4.1
    container_name: cassandra-node2
    networks:
      cass-net:
        aliases:
          - cassandra-node2
    environment:
      - CASSANDRA_CLUSTER_NAME=meu_cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node2
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    volumes:
      - cassandra-data2:/var/lib/cassandra
    ports:
      - "9142:9042"       # expõe porta 9042 em 9142 local
      - "7299:7199"
    depends_on:
      - cassandra-node1
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra-node3:
    image: cassandra:4.1
    container_name: cassandra-node3
    networks:
      cass-net:
        aliases:
          - cassandra-node3
    environment:
      - CASSANDRA_CLUSTER_NAME=meu_cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node3
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    volumes:
      - cassandra-data3:/var/lib/cassandra
    ports:
      - "9242:9042"
      - "7399:7199"
    depends_on:
      - cassandra-node1
      - cassandra-node2
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  cass-net:

volumes:
  cassandra-data1:
  cassandra-data2:
  cassandra-data3:
